Add config files
AreaFiftyLAN/lancie-admin pull request #1
Opened 2017-01-09 15:53 UTC by FrancisBehnen

2017-01-09 15:53 UTC, FrancisBehnen commented
Just edit the config files for the admin project

2017-01-09 15:56 UTC, TimvdLippe commented on polymer.json
> +    "src/lancie-home-page/lancie-home-page.html",
You can remove these for now

2017-01-09 19:00 UTC, FrancisBehnen commented
Is de lancie-admin repo al gekoppeld aan het slack channel trouwens?

2017-01-09 19:01 UTC, TimvdLippe approved these changes
Small comments, other than that LGTM

2017-01-09 19:01 UTC, TimvdLippe commented on gulpfile.js
> +  activities: '340x340',
This object should be empty as there are no images yet in `lancie-admin`

2017-01-09 19:01 UTC, TimvdLippe commented on package.json
> +    "serve-build": "yarn run ensure-images && node ./node_modules/polyserve/bin/polyserve build/bundled/ -p 5101 -P h2 --proxy-path api --proxy-target http://localhost:9000/api/"
We should also fix this in `lancie-frontend`, but this line is redundant. We can (apparently) already do `yarn run serve build/bundled`

2017-01-09 19:23 UTC, martijnjanssen commented on package.json
> +    "node": ">=5.0.0"
@TimvdLippe we are running on travis node version 6.0.0, should we update this, too?

2017-01-09 19:24 UTC, martijnjanssen commented on polymer.json
> +   "scripts/*"
I don't think we need this folder in this repo. I vote for removal of this one.

2017-01-09 19:25 UTC, TimvdLippe commented on package.json
> +    "node": ">=5.0.0"
Yes we can

2017-01-09 19:25 UTC, martijnjanssen commented on sw-precache-config.json
> +   "urlPattern": "/https:\\/\\/fonts\\.googleapis\\.com\\//",
Go ahead and remove the font. lets try to go for minimal size in this repo and use system fonts only. :package:

2017-01-10 09:33 UTC, martijnjanssen requested changes
Looks good, but lets remove some stuff. :)

2017-01-10 09:33 UTC, martijnjanssen commented on bower.json
> +    "app-storage": "PolymerElements/app-storage#^0.9.8",
The app storage can be removed for now.

2017-01-10 09:33 UTC, martijnjanssen commented on bower.json
> +  "private": true,
I'm not sure we need this flag

2017-01-10 09:33 UTC, martijnjanssen commented on gulpfile.js
> +  slider: '2000x500,scale-down'
We won't be needing the slider, unofficial and activities image options.

2017-01-10 09:33 UTC, martijnjanssen commented on package.json
> +    "node": ">=5.0.0"
Why not node 6.0.0?

2017-01-10 09:33 UTC, martijnjanssen commented on polymer.json
> +   "scripts/*"
We do not have scripts yet, and may never have them. In the frontend we use them for data. I'm pretty sure we don't need that in this repo.

2017-01-10 09:33 UTC, martijnjanssen commented on polymer.json
> +    "src/lancie-password/lancie-request-password-reset-success.html"
All these pages can be removed as of now, we do not require these for lazy-loading.

2017-01-10 09:33 UTC, martijnjanssen commented on sw-precache-config.json
> +   "urlPattern": "/https:\\/\\/fonts\\.googleapis\\.com\\//",
No fonts are needed right now.

2017-01-12 18:22 UTC, martijnjanssen requested changes
I think we have almost fixed everything now.

2017-01-12 18:22 UTC, martijnjanssen commented on bower.json
> +    "google-map": "GoogleWebComponents/google-map#~1.1.14",
Google maps? :)

2017-01-12 18:22 UTC, martijnjanssen commented on .travis.yml
> +script: "yarn run build"
Single quotes?

2017-01-12 21:59 UTC, TimvdLippe requested changes

2017-01-12 21:59 UTC, TimvdLippe commented on gulp-tasks/project.js
> +    swConfig: global.config.swPrecacheConfig,
Please also incorporate the changes of https://github.com/AreaFiftyLAN/lancie-frontend/pull/393

2017-01-12 21:59 UTC, TimvdLippe commented on package.json
> +    "serve-build": "yarn run ensure-images && node ./node_modules/polyserve/bin/polyserve build/bundled/ -p 5101 -P h2 --proxy-path api --proxy-target http://localhost:9000/api/"
Yup removed, per https://github.com/AreaFiftyLAN/lancie-frontend/pull/393

2017-01-12 21:59 UTC, TimvdLippe commented on polymer.json
> +  "sourceGlobs": [
`sources` per https://github.com/AreaFiftyLAN/lancie-frontend/pull/393

2017-01-12 21:59 UTC, TimvdLippe commented on polymer.json
> +  "includeDependencies": [
`extraDependencies` per https://github.com/AreaFiftyLAN/lancie-frontend/pull/393

2017-01-13 21:23 UTC, martijnjanssen approved these changes

2017-01-13 21:33 UTC, TimvdLippe approved these changes

2017-01-13 21:34 UTC, merged