[WIP] Deployment to docker container
AreaFiftyLAN/lancie-admin pull request #11
Opened 2017-01-25 22:20 UTC by martijnjanssen

2017-01-26 08:01 UTC, praseodym requested changes

2017-01-26 08:01 UTC, praseodym commented on Dockerfile
> +RUN yarn run build
Moet dit 2x?

2017-01-26 08:01 UTC, praseodym commented on Dockerfile
> +COPY ./build/bundled/. /usr/share/nginx/html
Hier kopieer je spul vanaf buiten je container naar je container. Bedoel je niet gewoon `cp`?

2017-01-26 08:01 UTC, praseodym commented on Dockerfile
> +RUN apk del nodejs-lts git
Een Docker image bestaat uit verschillende layers die over elkaar worden gelegd. `docker build` maakt voor elk commando (dus ook elke `RUN`) een layer aan. Die layers worden niet samengevoegd (dat is nog een experimentele feature) wat betekent dat als je in layer `n` iets toevoegt en in layer `n+1` weer verwijdert de bestanden nog steeds deel uit maken van je image (en dat is dus ruimteverspilling). 

Om dit op te lossen kun je alle commando's in één `RUN` doen door ze met `&&` aan elkaar te plakken. Zie bijvoorbeeld https://github.com/praseodym/docker-znc-armhf/blob/master/Dockerfile waarbij de build dependencies worden geïnstalleerd en in dezelfde layer nog worden verwijderd, zodat ze geen deel uitmaken van het image.

2017-01-26 08:03 UTC, praseodym commented
Vergeet ook de `.git` folder niet in je `.dockerignore`.

2017-01-26 08:06 UTC, TimvdLippe commented on Dockerfile
> +RUN yarn run build
Yes. One executes a specific gulp task, the other the default one. The default one does not include optimize-images (by design)

2017-01-26 08:07 UTC, TimvdLippe commented on Dockerfile
> +RUN apk del nodejs-lts git
Would it be better to put all these run commands in a script to keep it readable?

2017-01-26 08:15 UTC, martijnjanssen commented on Dockerfile
> +COPY ./build/bundled/. /usr/share/nginx/html
Dit kopieert dus niet de contents van de build die net uitgevoerd met als resultaat de `./build` naar de locatie om het te serven? Als dat zo is klopt het inderdaad nog niet.

2017-01-26 08:33 UTC, praseodym commented on Dockerfile
> +COPY ./build/bundled/. /usr/share/nginx/html
Nope, dat doe je gewoon met `cp` In een `RUN`.

2017-01-26 22:00 UTC, martijnjanssen commented
The Dockerfile now works correctly, the pages are served. A proper nginx config still has to be added.

Another problem is the size of the container, it currently is a whopping 194MB, which is way too big considering that the nginx-alpine base image is only 54.3MB. Some packages are being installed, but are uninstalled afterwards. I'm not quite sure what causes the size increase, I could use some help with that.

2017-01-26 22:12 UTC, TimvdLippe commented on Dockerfile
> +EXPOSE 8080
Why not 5100?

2017-01-26 22:12 UTC, TimvdLippe commented on README.md
> +You can now view the admin page on `localhost`,
Add the port here too

2017-01-26 22:16 UTC, martijnjanssen commented on Dockerfile
> +EXPOSE 8080
Because the default nginx config serves on 8080, so this has to be changed in our custom config.

2017-01-26 22:55 UTC, martijnjanssen commented
Are we going to add the nginx.conf in here or are we going to create an issue for it?

2017-01-27 12:59 UTC, martijnjanssen commented
The image is now 57.5MB, I think this is ready to go. The `nginx.conf` has basic functionality, but has to be expanded to function correctly. I will create a separate issue for that.

2017-01-27 14:04 UTC, praseodym reviewed
Wat is de toegevoegde waarde van de `nginx.conf`?

2017-01-28 14:03 UTC, praseodym requested changes
Je doet niks met de `nginx.vh.default.conf`? En er lijkt ook geen speciale configuratie in te staan (404 page?).

2017-01-28 14:03 UTC, praseodym commented on build.sh
> +
ik zou hier nog nog `set -e` toevoegen zodat het script afsluit bij fouten

2017-01-28 14:08 UTC, martijnjanssen commented
De config zorgt ervoor dat hij alle bestaande resources returnt, maar dat als de resource niet gevonden is dat hij de index.html returnt.

2017-01-28 14:11 UTC, praseodym commented
Had over de `try_files` heen gekeken :-)

2017-01-28 14:12 UTC, praseodym approved these changes

2017-01-28 14:12 UTC, praseodym commented
Wel even squashen natuurlijk :')

2017-01-28 14:13 UTC, merged